### ISSUE TITLE
Verify transaction using absolute expiration time cannot be replayed

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#110]
Duplicate Transaction Checking needs to make sure that transactions have a maximum absolute expiration time that is within range of the duplicate checks.

**Comment by theoreticalbts** [comment]
I'm going to write a test case for this.

**Comment by theoreticalbts** [comment]
With the current implementation's default parameters, it seems like an absolute expiration transaction would only be valid for ~~1024~~ 64k blocks (~~85 minutes~~ 18 hours with 1-second blocks) before its expiration.

Dynamic block interval makes this a hard problem, because increase of block interval size will make the algorithm @bytemaster outlines assume the ~~undo buffer~~ duplicate check buffer extends further back in time than it actually does, opening the possibility of a replay.

**Comment by theoreticalbts** [comment]
I think it may help to formally define exactly what conditions we need to enforce, and then prove that whatever algorithm we implement enforces these conditions.

Let `b0, b1` be blocks with `b0` an ancestor of `b1`.  For any transaction `tx` with absolute expiration, let `valid(tx, t)` if `tx` is valid in block with timestamp `t`.  For any block `b`, let `dup_window(b)` be the set of blocks which are duplicate checked as of block `b`.

Then we want to write an implementation of `valid()` and `dup_window()` which enforce the following condition:
- If `valid(tx, b0.timestamp)` and `valid(tx, b1.timestamp)`, then `b0` is in `dup_window(b1)`.

**Comment by theoreticalbts** [comment]
Previous comment's condition is not quite right, because it seems likely that `valid()` and/or `dup_window()` will have an additional dependency on chain state (block interval).  Revised condition:
- If `valid(tx, b0.timestamp, b0.state)` and `valid(tx, b1.timestamp, b1.state)`, then `b0` is in `dup_window(b1, b1.state)`.

Included in `b.state` is the block interval and/or some other chain state (i.e., @bytemaster proposed a two-phase scheme for updating block interval).

**Comment by theoreticalbts** [comment]
I think we need to include a `not_valid_before` field in the transaction header or ops.
Then define `valid(tx, b.timestamp, b.window_begin)` as the following inequalites:
- `b.window_begin <= tx.not_valid_before <= b.timestamp <= tx.not_valid_after`

And define `dup_window( B, B.window_begin )` as:
- `{ b : b.timestamp >= B.window_begin }`

To prove the condition in the previous comments, we must start with
`valid(tx, b0.timestamp, b0.state)` and `valid(tx, b1.timestamp, b1.state)`, that is:
- `b0.window.begin <= tx.not_valid_before <= b0.timestamp <= tx.not_valid_after`
- `b1.window.begin <= tx.not_valid_before <= b1.timestamp <= tx.not_valid_after`

And we must prove `b0` is in `dup_window(b1, b1.state)`, that is:
- `b0.timestamp >= b1.window_begin`

The proof is straightforward application of the fact that `<=` is transitive:
- Since `tx.not_valid_before <= b0.timestamp` and `b1.window_begin <= tx.not_valid_before`,
- It follows that `b1.window_begin <= b0.timestamp`.

**Comment by bytemaster** [comment]
This is a non-issue because we keep all transaction IDs around until they expire.  You cannot include the same transaction twice.
