### ISSUE TITLE
When can vesting_balance_object's be freed?

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#123]
Currently vesting balance objects are simple_index which is fast, but assumes they are never freed.   With vesting balances being a feature available to users who may create them "at will", we probably need to free these vesting balances whenever the balance goes to 0.  

This means converting to a multi-index container and using a hash on the id.

This shouldn't result in a hardfork, it merely optimizes memory use.

**Comment by VoR0220** [comment]
by freeing them, do you mean removing them from the database?

**Comment by bytemaster** [comment]
Yes

**Comment by nathanielhourt** [comment]
The issue here is that some `vesting_balance_object`s are created by core evaluation, and those ones are expected to live forever. Even if they get emptied, the current implementation expects them to be retained so it can deposit more funds into them. This is how workers get paid, and it looks like #142 is requesting another case where this happens. Those ones can't be removed, but we could remove others if we added a way to distinguish between them.

**Comment by VoR0220** [comment]
I'm trying to find out more about what else is tied to vesting_balance_object. Correct me if I'm wrong, but this is meant to be applied to a User Issued Asset, correct? Perhaps you could add a constant time based parameter so that after a certain amount of time being emptied they are then removed from the database? Or perhaps you could set it up so that different rules apply to assets than do workers?

**Comment by theoreticalbts** [comment]
The thing is that VBO's cannot be deleted, because subsequent deposits to the same VBO will result in it being resurrected, and the chain must remember the parameters.  In any case we don't know _when_ the user will withdraw from the VBO, so even if we e.g. added a flag to a VBO allowing deposits to be disabled (which would allow the VBO to be culled from the database on destruction), we'd still have to set the fee as if the VBO would live forever (because the user could always make it live forever by simply not withdrawing from it).

So I guess the proper way to make VBO's which can be safely removed from the database is to allow creation of VBO's which don't allow deposits, then move the funds from such a matured VBO to the owning user's account automatically at maturity.  NB we still have to allow the creation of VBO's which allow deposits, as those are used for worker and witness pay.

It sounds almost like we want a different object type for this.

**Comment by theoreticalbts** [comment]
This sounds a lot like a wontfix.
