### ISSUE TITLE
How to remote connect by websocket

### ISSUE THREAD

**Issue by cgafeng** [cryptonomex/graphene#132]
my witness_node running on 192.168.1.132 and try to run graphene-ui on other computer, then get the connect error, what's the suggest?

```
WebSocket connection to 'ws://192.168.1.132:8090/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

**Comment by emfrias** [comment]
when you run `witness_node --rpc-endpoint`, by default it will listen on 127.0.0.1 port 8090, meaning it will only accept connections from the same machine the witness_node is running on.  This is for security; since the websocket connection is unencrypted, someone could eavesdrop on connections from other computers.

However, since this is just a testnet, you're probably not worried about security.  Run your witness node like: `witness_node --rpc-endpoint=0.0.0.0:8090` and it will allow anyone to connect.

**Comment by cgafeng** [comment]
thx, i will try it later.
