### ISSUE TITLE
Document how bulk discount mechanics should work

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#169]
We have not really discussed much about the details of the bulk discount mechanics.  I see some code is implemented, e.g. https://github.com/cryptonomex/graphene/blob/master/libraries/chain/account_object.cpp#L120-L129 but it is difficult to write a unit test without being clear what the code is _supposed_ to do, which is itself difficult to figure out without economic motivation.

This feature badly needs:
- Technical system documentation on how the mechanics are supposed to work
- End-user documentation and marketing materials aimed to educate users about how to take advantage of the feature

To me this feature seems overly complicated and the justification isn't clear.  I am currently in favor of removing the feature, but I might change my mind after some discussion.

**Comment by bytemaster** [comment]
After a user pays $X in total life time fees, they start getting a discount on future fees that phases in linearly over time until they have paid a total $Y in lifetime fees after which they qualify for the maximum discount.

The goal is to reduce fees for heavy users of the system because these are the people we want.    

This particular feature violates the principle that given a fee schedule and transaction a user should be able to determine the required fee.   With bulk discounts they also need to know the total lifetime fees paid by the fee paying account.   This number may be a moving target.   

I support removing this feature for now and revisiting it with community approval for a future hard fork.
