### ISSUE TITLE
get required fees api call

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene#207]
I imagine this API call would work something like this:

accept an array of operations and and an asset id and return and array of int amounts (same index as the operations in the parameter and same type of asset).  It may be beneficial to always return the fee in CORE and in the secondary asset type.

**Comment by jcalfee** [comment]
Please consider an enhancement and remove the asset_id_type from the parameter and instead obtain this from each operation.  

`vector<asset> get_required_fees( const vector<operation>& ops, asset_id_type id = asset_id_type() )const;`

**Comment by theoreticalbts** [comment]
The fee asset ID is included in the operation, so you can use any asset to pay for any operation.  For example if I'm transferring you USD, I can pay the fee in USD (the asset being sent), BTS (the core asset) or even GLD (some unrelated third asset).

What we could do is read the asset ID out of each operation.  In this case, if you have a tx with two operations, and the user wants to pay for the first operation with CORE and pay for the second operation with USD, you would set `ops[0].fee = core.amount(0); ops[1].fee = usd.amount(0);` and then issue the API call `get_required_fees(ops)` which would give you the (nonzero) amounts.

It seems unlikely that a user would ever have a reason to pay different ops' fees in different assets.  I have a feeling 99% of advanced users will use CORE for all fees because going through the fee pool would just be extra cost.

**Comment by jcalfee** [comment]
I re-opened with an small enhancement but this is not needed .. the existing api works fine for any case we have now.
