### ISSUE TITLE
Upstream secp256k1-zkp API has changed

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene#226]
Followed instruction in Readme.md

```
CMake Error in libraries/fc/CMakeLists.txt:
  Imported target "secp256k1" includes non-existent path

    "/home/clayop/graphene/libraries/fc/vendor/secp256k1-zkp/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

```

**Comment by clayop** [comment]
Related log

```
clayop@ubuntu:~/graphene$ git submodule update --init --recursive

...

Cloning into 'vendor/secp256k1-zkp'...
remote: Counting objects: 2907, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 2907 (delta 54), reused 49 (delta 49), pack-reused 2843
Receiving objects: 100% (2907/2907), 1.16 MiB | 1.37 MiB/s, done.
Resolving deltas: 100% (2069/2069), done.
Checking connectivity... done.
fatal: reference is not a tree: bd067945ead3b514fba884abd0de95fc4b5db9ae

...

Unable to checkout 'bd067945ead3b514fba884abd0de95fc4b5db9ae' in submodule path 'libraries/fc/vendor/secp256k1-zkp'
Failed to recurse into submodule path 'libraries/fc'
```

**Comment by clayop** [comment]
It seems that submodule should be changed.
https://github.com/ElementsProject/secp256k1-zkp/commit/71ed475ea53ff4576b7344762584b752a824c60f

**Comment by vikramrajkumar** [comment]
Upstream `secp256k1-zkp` has rebased AND changed their API.

As a temporary fix, I have redirected the remote for the `secp256k1-zkp` submodule inside `fc` to point at our own copy: https://github.com/cryptonomex/fc/commit/458b601774c36b702e2d4712320b5d53c6b2ee1c

Those with already checked-out copies will want to manually edit their local remote to reflect this change, or otherwise clone fresh.

Ultimately we will want to update `fc` to work again with the new API in the latest upstream version, which I will assign to @bytemaster because he did the initial integration, I believe.

**Comment by clayop** [comment]
Building works now.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#60
