### ISSUE TITLE
Some api calls accept account ids, others accept account names, probably they should always allow either 

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#26]
> Verify if this is true, not so sure now.

**Comment by jcalfee** [comment]
I have a lookup in JavaScript that does something like this.  It is a good place to plugin other servers to verify the results and add fault tolerance.  Basically it detects single numbers and treat them as an object id as long as it knows its type, or it takes the object id directly (n.n.n), or it sees that it starts with a letter and does a lookup to get the object id..

**Comment by bytemaster** [comment]
All witness node API methods deal in account ids except for ones that are doing lookup / listing by name.   The witness node needs to be efficient in responding to queries so we should offload the lookup/conversion to the client.

All wallet APIs should support either because those are more user facing.  They appear to be uniform as well.
