### ISSUE TITLE
Can we adjust the API time strings to be more like the ISO 8601 Extended Format

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene#368]
Xeroc noticed that at 12 second expiration times in FF with a NTP synced time all his transactions were expired before they were sent.  I re-created the issue and here is what I found: 

The head block time I get from the server does not have a Z on the end (zulu).. So, chrome treats it as zulu anyways but FF tries to convert it to a local timezone.  I had to change the timezone on my computer to UTC+2 to match yours.  Then I was able to see the problem.  For now I can add the Z.. Here is the test data:
FF:
```new Date("2015-10-09T15:35:32").toString()
"Fri Oct 09 2015 15:35:32 GMT+0200 (EET)"
new Date("2015-10-09T15:35:32Z").toString()
"Fri Oct 09 2015 17:35:32 GMT+0200 (EET)"

``````
Chrome:
```new Date("2015-10-09T15:35:32").toString()
"Fri Oct 09 2015 17:35:32 GMT+0200 (EET)"
new Date("2015-10-09T15:35:32Z").toString()
"Fri Oct 09 2015 17:35:32 GMT+0200 (EET)"```
I would like to know if we can change the witness node to confirm to a standard format to avoid this problem in other places: http://es5.github.io/#x15.9.1.15
``````

**Comment by emfrias** [comment]
This gets my vote.  I kept a private fork of fc that added the Z for a while because it was so useful (now I'm using boost posix_time directly to avoid forking).

If we're considering changes that alter the way times print, another quirk is that time_point drops fractional seconds when it goes to/from a variant.  I'd rather it keep microseconds and require an explicit cast to time_point_sec if you want to drop them.

**Comment by theoreticalbts** [comment]
Possibly related (closed) issue:  https://github.com/cryptonomex/graphene-ui/issues/231

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#99
