### ISSUE TITLE
Need ability to poll for all holders of an asset

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene#400]
Let's say I sell an asset. Some people buy it to trade it, others to buy it and hold it so that they get a kickback on the success of the project.

How do I know who is holding that asset so that I can pay them? It would be great if we could tie in the scheduled and recurring payments feature with this polling feature so that we don't have to pay them out manually. 

@xeroc suggested that I post this desire here. 
Thank you, kenCode

**Comment by xeroc** [comment]
Ivan from CCEDK has asked for this features aswell

**Comment by xeroc** [comment]
I got more people asking for this feature!

**Comment by abitmore** [comment]
Technically we can add an index in the database for this feature, however query of that index is relatively expensive since you don't know how many records will be there. So pagination is needed, but the paginated result could be inconsistent since the records may change every block. So best to use it in debug mode (#596) only, or call it only when distribution of the asset is in a frozen stat.

By the way, some holders may put all their assets in orders and/or collateral, so additional indexes are needed.

**Comment by xeroc** [comment]
@abitmore alternatively to limiting this to debug mode would be to add another API (similar to crypto_api, or network_node_api) that requires authentication. Then those that need that feature need to properly authenticate at the witness node and are fine to use more resources. That way, resource-hungry calls are limited to authenticated users and you could even query indices from collateral or orders.

**Comment by abitmore** [comment]
@xeroc I'm not sure if this call (to any asset) can be finished in 3 seconds (a block interval), depends on how much data need to be returned, and how powerful the hardware of API server is, and maybe network latency factor. If it need more than 3 seconds, even if you limit that only one client can do this at a time, the result may be inconsistent in some cases.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#107
