### ISSUE TITLE
Tx operation is sometimes not returned in get_block

### ISSUE THREAD

**Issue by roadscape** [cryptonomex/graphene#426]
I encountered an operation in a block that's never returned in get_block.

The op type is `committee_member_update_global_parameters`. There may be others but I found this one while looking thru committee-account history.

```
get_object 1.11.91568
[{
    "id": "1.11.91568",
    "op": [
      31,{
        "fee": {
          "amount": 4000000,
          "asset_id": "1.3.0"
        },
        "new_parameters": {
              ....snip......
    ],
    "block_num": 293247,
    "trx_in_block": 0,
    "op_in_trx": 1,
    "virtual_op": 57532
  }
]



get_block 293247
{
  "previous": "0004797eecbaeb9e4959f41a4238812c2545446f",
  "timestamp": "2015-10-23T22:50:00",
  "witness": "1.6.26",
       ...snip...
  "transactions": [],
  "block_id": "0004797f2ca5c392b1a378a3354d8ad9a5a4701b",
  "signing_key": "BTS7W9Ekx5vUi1uwLH7rtSFbTRdpQboE4jMukfgW4dGpwNH9ZKHrb",
  "transaction_ids": []       <-------- where is the tx? -------
}
```

I was expecting get_block to always return all transactions and operations in the block. 
It's strange that in this case it doesn't..

**Comment by theoreticalbts** [comment]
What's going on here is that a proposal is executing.  A committee proposal is processed spontaneously by the network at its expiration, (whereas more "classical" blockchain behavior is for state changes to always be triggered by a user-broadcast transaction).

This is not a bug, but it is a hard case for wallets, chain explorers, and other higher-level layers to deal with.  And it certainly does initially look like a referential integrity violation (operation history objects referencing transaction numbers that don't exist).  What we need to do is improve recording of the chain history because the higher-level tooling really "wants" records of proposed transaction execution analogous to the records of regular transaction execution.  Thus, we need to generate virtual transaction objects for proposed transactions when they execute.

**Comment by roadscape** [comment]
Thanks Ben, makes sense. Virtual txs for any "derived" state changes would be great!

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#119
