### ISSUE TITLE
Feature -> UIA -> Field to store IPFS token for digital certificates when issuing assets

### ISSUE THREAD

**Issue by juanfranblanco** [cryptonomex/graphene#444]
This can be a very simple feature, when issuing tokens from an UIA, the tokens can linked to an IPFS token that will hold the digital certificate. This will allow to quickly provide similar functionality to Factom or other specialised Digital Assets.

**Comment by xeroc** [comment]
Great Idea .. but I don't see why this needs to be a graphene feature .. can't you simply issue from a known organization and use a public memo to do the very same thing already now?

**Comment by juanfranblanco** [comment]
The issuing will be centralised but once the asset is issued, you can use the ipfs file for verification and traceability of the asset it belongs to. Yes you still need to trust a third party (the certificate issuer) but it avoids an step in the verification, providing further trust.

This might not be as simple as I thought (never is) you might want to have a certificate associated with a UIA, which will mainly give you shares on that property. Or you might want to attach a certificate with the undividable tokens. And more complex, a collection of certificates associated with an UIA to demonstrate the total issuance, of divisible assets. ie OTC Stocks.

Starting with a very simple scenario, UIA <-> Certificate, it will provide a great demonstration of what can be done already with bitAssets without relying to complex smart contracts, and satisfying most business needs.

**Comment by theoreticalbts** [comment]
Publishing auxiliary information on the chain that the witnesses do not validate (other than ensuring an anti-spam fee has been paid) can be done with the `custom_operation`.  Currently witness_node throws away the results of `custom_operation`, i.e. you'd have to modify the client to index the data (or maybe create an external application which walks through the blocks and indexes it).

We originally envisioned a plugin system for use cases like yours, but it is currently undocumented and extremely unpolished (e.g. a plugin should be able to add API calls but there is currently no way to do this).

I'm not sure about your usage of "certificates," but if a certificate is simply an assertion by one public key K that another public key K' is authorized to perform a certain action, this idea is already encapsulated in multisig.  Just set the account which can perform the action to have a threshold of 1 and K, K' as keys with weights of 1, effectively a 1-of-2 multisig.  Then this is effectively a blockchain-level assertion that K' is authorized to perform any action K can perform.

If you need your assertions in the existing X509 cert format for interoperability, you'd need to essentially publish a hash of the cert and store it somewhere else.  IPFS seems like it would be a good choice for doing the hash-to-content mapping.

The real problem here is indexing and access control.  You really want to use the chain for this since the chain knows at any point in time who is authorized to update the current cert hash, and then you can inject that information into your indexing (don't index anything that was included in the chain at time t, unless it was signed by the asset object's owner at time t).  Then you need to add an API call to get the desired information (what is the current cert hash attached to an asset?  what cert hash was attached to an asset at some time in the past?) out of the `witness_node`.  Which is exactly what the plugin system should do, it just doesn't.

Related:  #246

**Comment by juanfranblanco** [comment]
Yes I looked at the code, and show some of the plugin stuff (also wondered what was that and how to use it ;) ) That will be a great addition for custom business models and / or extra storage.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#126
