### ISSUE TITLE
Refactor naming of overloaded methods

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#472]
`fill_order` and `match` (ab)use function overloading.  The `match()` call [here](https://github.com/cryptonomex/graphene/blob/7a1eae4d68e87222d68bbace310c3d1f9d5dfc74/libraries/chain/db_update.cpp#L352) in `clear_expired_orders()` is matching a `force_settlement_object` against a `call_order_object` (and confusingly the inner loop creates an `itr` which hides the outer loop's iterator which is also called `itr`).

Likewise the `fill_order` [here](https://github.com/cryptonomex/graphene/blob/7a1eae4d68e87222d68bbace310c3d1f9d5dfc74/libraries/chain/db_market.cpp#L504) is overloaded version for call order (hence takes no taker flag parameter) while the call a couple lines down is overloaded version for limit order (and does use taker flag parameter).

These overloads should be given different names.

Related:  #468

**Comment by bytemaster** [comment]
These overloads were given the same names so that they could be used with a TEMPLATED match function.  Changing the names on these methods would require implementing several variations on the MATCH function as well which increases code complexity and opportunity for bugs.

Having the 'itr' variable hidden is less than ideal and can be fixed, but the methods should not be renamed.
