### ISSUE TITLE
Can we make the UIA name longer than 16 characters please

### ISSUE THREAD

**Issue by kenCode-de** [cryptonomex/graphene#520]
The Smartcoins POS systems allow the merchant to automatically offer their rewards with each customer purchase. In the POS settings screen though, there are so many UIA's listed in there already, it would be nice if the merchant's UIA were easier to find, and more explanatory. This way when the customer looks in their mobile wallet, they will see that merchants UIA as a nice little reminder and there is no question what it's for.

STARBUCKS.REWARDS for example is 17 characters. 
MEDIAMARKT.REWARDS is 18 characters. 
CIRCUITCITY.REWARDS is 19 characters. 
ALBERTSONS.REWARDS is 18 characters. 
JOES.COFFEE.ON.MAIN.STREET is 26 characters.

Some small businesses have more than 1 location (like Joe's Coffee) and it would be nice if they could offer their own token too. You get the point. Can we please expand UIA length to say 32 chars?

**Comment by dnotestein** [comment]
IIRC, the issue here is that this is the "SYMBOL" for the UIA. The symbol is of a fixed size so that it can show properly in the exchange buy/sell screens for example. The UIA can also have a description, which is where you can assign a long descriptive name to the UIA. You could then modify your wallet, for example, to allow a user to hover over the symbol to display the descriptive name, although the standard wallet already allows you to click on the asset symbol and go to the page that includes the description, I think.

**Comment by kenCode-de** [comment]
Well, those screens are reactjs so if they are also responsive then they will scale automatically.  If there is just too many chars then truncate the string and append a ... to the end with a tooltip. 
The mobile wallet screens are just too tiny to add the asset description, so we have to show something more descriptive for the asset symbol.

**Comment by dnotestein** [comment]
This would require a hardfork plus webwallet GUI changes. And ultimately, this is just another "guess" at what the proper length of this fixed field should be (original guess was 16, you're suggesting 32). Although making this change probably seems trivial, in practice it's not, because it's a fixed parameter of the blockchain (and there's GUI and potentially other 3rd party code that relies on it). Unless you're willing to fund the change, I doubt it's likely to get approval.

**Comment by roadscape** [comment]
I like the idea, though it raises complications.. what about this as a compromise: put the "nice name" as the first line of the asset description. And in the mobile app (where space is limited but you need a nice display name) only show this first line.

If asset descriptions can't have newlines, you could use a period, semicolon, etc to do the same thing.

**Comment by dnotestein** [comment]
I think this is the best solution (the compromise idea), I had the same idea in mind.

**Comment by kenCode-de** [comment]
Ok, I can work with that. So in the mobile wallets I should just show this as the asset in the Balances section of the homescreen? 

asset['options']['description']

**Comment by xeroc** [comment]
I would go like this
- check if there is a `\n` in the description
- if there is, display `SYMBOL + first line of description` as name
- if there is not, just display `SYMBOL` as name

**Comment by kenCode-de** [comment]
ok, will try this, thanx guys :)
