### ISSUE TITLE
compiling on SunOS x86_64 fails

### ISSUE THREAD

**Issue by xmr-karnal** [cryptonomex/graphene#522]
I'd like to get several witnesses running on SmartOS. Unfortunately, the compilation is failing.

See here https://bitsharestalk.org/index.php/topic,21053.0.html

I'd like to port graphene to pkgsrc (it will then be available for NetBSD and SmartOS) and need to get past this. Any help welcomed.

**Comment by theoreticalbts** [comment]
It seems the issue in the linked thread is that the C++ library for the compiler you're using may `#define int8_t char` instead of `typedef int8_t char`, which makes the compiler complain that providing template overrides for both `char` and `int8_t` is wrong (since by the time it gets to template processing the preprocessor's changed `int8_t` to `char`).  Or maybe the compiler doesn't allow different template overrides for a typedef'd alias.  You may be able to get past this particular error if you simply #ifdef out one of these two overrides in typename.hpp

I'm not sure if stdlib / compiler that does this is C++11 compliant, if your compiler does not support C++11 then this port is almost surely doomed (unless you want to re-write large parts of Graphene).  If you need compiler specific command line options to enable C++11 (for example g++ uses `-std=c++11`) you may have to modify `CMakeLists.txt` to provide these flags.

As none of the core developers have SunOS machines, and it is very much a niche platform in 2016, we can't officially support it.  But good luck with this port!

**Comment by xmr-karnal** [comment]
It's not as niche as it might seem :) SmartOS is and has been under heavy development for the last years, the Illumos (https://en.wikipedia.org/wiki/Illumos) project is alive and well, and thousands of virtual machines run solaris at https://www.joyent.com/public-cloud and elsewhere.

I reached the same conclusion as you regarding int8_t being the same as char, it may be a perk of the solaris platform. My programming skills are limited though, and I'm unsure how to best fix it.

The problem (almost) surely isn't the compiler, it's g++ (GCC) 4.9.3.

Later today I may have some time to try and fix this, but regardless, if you'd like shell access to this instance, I'd be more than happy to provide login credentials.

**Comment by xmr-karnal** [comment]
bump

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#150
