### ISSUE TITLE
`propose_parameter_change` does not behave as documented

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene#526]
According to the documentation I can use `propose_parameter_change` to change individual fees.

But, if I only want to change the `per_kb_fee` and thus only have that in the fee object the call add the default `fee` value as given in the GENESIS block and not from the currently installed fees

**Comment by theoreticalbts** [comment]
> According to the documentation I can use `propose_parameter_change` to change individual fees.

The `propose_fee_change` wallet command allows you to change individual fees, not `propose_parameter_change`.

Since setting individual fees isn't implemented in `propose_parameter_change`, [the very first line](https://github.com/cryptonomex/graphene/blob/d8cd48d6adba1b59df79d5374089b609ef7982b1/libraries/wallet/wallet.cpp#L2179) in `propose_parameter_change` implementation is supposed to disable changing fees entirely.  The only wallet command that's supposed to be able to change fees is `propose_fee_change` [1].

Can you provide the specific wallet command you used?

[1] If you didn't have access to this wallet command, with some inconvenience and manual construction of tx / operations, technically you _could_ use different wallet commands to propose a fee change.

**Comment by abitmore** [comment]
@xeroc according to the document of propose_parameter_change:

```
    changed_values: The values to change; all other chain parameters are
        filled in with default values (type: const variant_object &)
```

so current behavior is same as documented, a bit inconvenient though.

**Comment by xeroc** [comment]
I failed to realize the difference between "fee" and "parameter". Anyway, I have now written a basic python script for the committee to deal with this.
https://github.com/BitShares-Committee/Instructions
