### ISSUE TITLE
Fee pool - overpaying with satoshi amount of UIA

### ISSUE THREAD

**Issue by roadscape** [cryptonomex/graphene#528]
I create UIA 'ASSET' with 
- precision: 0
- CER: 1 ASSET = 100 BTS
- 2500 BTS in the fee pool

A transfer costs 30 BTS, and I pay the transfer fee using 1 ASSET.

100 BTS is withdrawn from the fee pool, even though only 30 BTS is required.

Would it make sense to have graphene leave the excess 70 BTS in the fee pool as opposed to (effectively) burning it?

**Comment by xeroc** [comment]
Oh .. so the issue is that you can only sell **integer** ASSET since precision is **0**.
Very nice find and IMHO not a desired behavior

**Comment by theoreticalbts** [comment]
It has nothing to do with the precision, precision is effectively only a UI thing and internally everything which actually happens is done with satoshis.

The real issue here is that you can only convert 1 satoshi of asset with the fee pool.  If you cash in too many satoshis, should you overpay the fee, or should you pay the exactly correct fee and leave the balance remaining in the fee pool?

In other words, when you're paying fees with a non-CORE asset, there will be some rounding error when converting the asset to pay fees (the system effectively forces the payer to overpay by 0-1 satoshis).  The question is whether this overpayment due to rounding should go to the network or the fee pool.  The current implementation sends it to the network.

It is obvious here because you've created an asset which is incredibly scarce / valuable, so the rounding error of 0.7 satoshi of ASSET is a meaningful amount -- 70 BTS.  Your precision makes 1 satoshi = 1 ASSET.

**Comment by theoreticalbts** [comment]
After some internal discussion, we decided that the current implementation's behavior is desirable / correct.

As the asset issuer, you can use `asset_claim_operation` to reclaim the `ASSET` which was exchanged for BTS.  Then you can sell the `ASSET` in the market for, say, 125 BTS, and use the proceeds to replace the 100 BTS from the fee pool.  (Of course to avoid paying excessive fees, the issuer should probably wait to do this until many `ASSET` have accumulated.)

If the `ASSET` is trading in the market for less than 100 BTS, the issuer should reduce the `core_exchange_rate` until the fee pool again becomes profitable for the issuer.  Essentially the fee pool is the issuer offering to buy `ASSET` for 100 BTS / satoshi, and the issuer makes a profit if this offer results in the issuer buying `ASSET` below its market price.

I think it's also instructive to imagine the events in reverse time order.  Imagine if you funded the fee pool by selling 20 `ASSET` for 125 BTS each.  Then you have 2500 BTS in the fee pool, at a core exchange rate of 100 BTS / ASSET you will get 25 `ASSET` -- you have a profit of 5 `ASSET` (since you started with 20 `ASSET` and turned it into 25 `ASSET`).

Since the issuer's already making a profit by selling at 100 BTS / ASSET, it's not really hurting them if the network claims the excess profit from rounding errors on customers trading small amounts.

Again, this effect can be minimized by setting precision so that one satoshi of your asset is a non-economically-meaningful quantity (for example if `ASSET` trades around 100 BTS / ASSET, a precision of 2 will limit rounding errors to less than 1 BTS.)
