### ISSUE TITLE
RE: #528 Fee pool - overpaying with satoshi amount of UIA

### ISSUE THREAD

**Issue by roadscape** [cryptonomex/graphene#531]
Regarding https://github.com/cryptonomex/graphene/issues/528

> After some internal discussion, we decided that the current implementation's behavior is desirable / correct.
> 
> [...]
> 
> Again, this effect can be minimized by setting precision so that one satoshi of your asset is a non-economically-meaningful quantity (for example if ASSET trades around 100 BTS / ASSET, a precision of 2 will limit rounding errors to less than 1 BTS.)

But what if I want one satoshi of my asset to be an economically-meaningful quantity?

I would appreciate if you also consider this scenario:
- `ASSET` is valued at 3.5 BTS / ASSET
- `ASSET` CER is 3 BTS / ASSET
- `ASSET` precision is 0

If the CER is lower than market value, then one can use the fee pool for profit. There could be an external incentive to pay fees using `ASSET` even when paying fees in `BTS` would be cheaper.

The worst case scenario is that a fee is 3.01 BTS.. this would require payment of 2 ASSET, and it would remove 6 BTS from the fee pool. My net gain is 1 BTS, but it **could have been 3.99 BTS** had the network not burned the remainder.

This is an issue I'm dealing with right now... and my options are:
1) Convince a dev to fix this behavior :)
2) Change the precision to decrease rounding losses (not ideal, & not possible?)
3) Lower the "face value" of 1 `ASSET` (not ideal)
4) Issue a new asset (also not ideal)

IMHO, as an asset issuer I'd rather have rounding issues work to my benefit.

I intentionally set the precision to 0 and the CER to 3 BTS. And my plan almost worked.. except for this quirk that **burns up to 75% of profits** from the fee pool. Please reconsider!

**Comment by abitmore** [comment]
> 1) Convince a dev to fix this behavior :)

Imo it's hard/expensive to fix, since the system is designed as unable to split a satoshi, neither for BTS nor for your ASSET, the amount below one satoshi hasn't been maintained. If benefit the issuer by rounding up, network would loss and become vulnerable.

In the real financial world, when value of a stock is getting too high, the company may split it. In BitShares, it can be done by share dropping 9x ASSET to holders for example.

Imo it should be possible to change the precision of an asset under some conditions. It would be an expensive operation if implemented, so perhaps nobody will use it..

**Comment by roadscape** [comment]
You misunderstand, I'm not asking to split satoshi's and the network does not lose any BTS. 

**I want an asset with a satoshi value of 1 cent.**

If a transaction costs 1/3 of a cent (1 BTS), it should not take 3 BTS from my pool. Just 1 BTS.

**Comment by roadscape** [comment]
Brought this up on today's mumble.. I guess it's a sound idea but comes down to economics.. so here's another pitch:

Low precision can be **great for usability**, but issuers are partially incentivized to make satoshis worthless just to avoid the loss described here.

A practical example: OPEN.USD -- with a precision of 2, a satoshi = 1 cent.
- If satoshi amounts are 1 cent, then the maximum loss per tx is approx 1 cent. 
- Assuming an average loss of 0.5 cents and a sustained 1 TPS, that's $157,000/year lost.

At the time of evaluating the incoming tx & adjusting the fee pool balance, does the witness node have to re-calculate the required op fees to ensure that the converted UIA amount meets it? If so, might it already have all the data it needs to leave behind the excess BTS?

**Comment by abitmore** [comment]
@roadscape in your example, if a user paid 1 cent as fee, assume that 1 cent equals to 3 BTS according to CER, it's fair that you as an issuer pay 3 BTS from the fee pool, although minimum required fee of the operation is 1 BTS. It's decided by the user that s/he wants to pay a fee equals to 1 cent (to the system), you get the 1 cent, you need to pay equivalent value in BTS to the system.

If someday the network is getting crowded, users have to increase fees so that their transactions can be recorded into the block chain, it's no reason for you to not pay out what amount the user requested. Imo the benefits of overpayment belongs to the system, not the asset issuer.

**Comment by theoreticalbts** [comment]
> issuers are partially incentivized to make satoshis worthless just to avoid the loss described here

Every `ASSET` that is converted through the fee pool is profitable for the issuer if they set their `core_exchange_rate` above the market rate.  In a transfer scenario, the sender's authorized the network to buy an amount of BTS equal to `fee + epsilon` from the fee pool on his behalf.  The issuer's role ends when the fee pool is paid the above-market rate for its BTS.  How the `(network, sender)` "partnership" divides the BTS (i.e. who gets the epsilon) is a matter between the network and the sender (and the current implementation resolves it in favor of the network).  The issuer's already gotten a profit because they've gotten a taker on their above-market offer.  If the issuer needs a higher profit margin to adequately incentivize keeping the fee pool funded, they should set a `core_exchange_rate` that's more favorable to themselves.

"Rounding errors go to the network" is a general principle employed throughout the Graphene code base, and the case for making an exception here simply isn't compelling.
