### ISSUE TITLE
Annual member does not receive cashback

### ISSUE THREAD

**Issue by pmconrad** [cryptonomex/graphene#539]
Forum thread: https://bitsharestalk.org/index.php/topic,21163.msg274253.html

tl;dr: account woodygar-1 has bought annual membership a couple of days ago but does not receive any cashback on his fees.
The account is its own referrer but not its own registrar. The registrar is identical to the lifetime_referrer.  referrer_rewards_percentage is 0, which is why the registrar/lifetime_referrer still receives a total of 80% of the fees while the account/referrer receives 0.
I think this is not the intended behaviour of an annual member account and probably a bug.

**Comment by woodygar** [comment]
Thanks for doing this for me pmconrad i appreciate it

**Comment by woodygar** [comment]
i bought full membership couldn't wait any longer but it does mean i have lost out a lot on fees and subscription but at least its ok now

**Comment by theoreticalbts** [comment]
It's not really a bug, more like counter-intuitive behavior.  The registrar sets `referrer_rewards_percentage` which determines the referrer / registrar split.  It is not such a big deal to set it to 0 since `referrer == registrar`.  However, `referrer` is non-constant -- becoming an annual member sets referrer to yourself.  So in the `referrer == registrar` case, the registrar's setting the percentage they give up when you become an annual member.

So what we need is an op which allows a registrar to update account's `referrer_rewards_percentage` upwards, and/or figure out a way to warn the registrar if they create an account with non-standard referral settings.

What _is_ a bug is that `referrer_rewards_percentage` is set to zero for accounts which are created at genesis, so anyone who upgrades a genesis account to annual will be in the same situation as OP.  I'm a little surprised nobody's been bitten by this yet.

It might technically be possible to HF the correct amount due to anyone who's in this situation.  It could potentially change VBO ID's, though, which makes things really icky because obviously ops reference VBO ID's, and we'll have to think hard about how to handle that...

**Comment by pmconrad** [comment]
This not just counterintuitive, it's wrong. The membership page in the GUI wallet clearly says that by buying annual membership you'll receive 50% cashback for one year: https://bitshares.openledger.info/#/account/pmc/member-stats/
I may be wrong, but I think that's what annual membership has always been about. In any case the implementation does not match the documentation.

**Comment by theoreticalbts** [comment]
The specification to which we implemented Graphene was that the referrer and registrar would decide on a split at account creation, and that the semantics of annual membership was to re-assign the referrer portion of the split to the account itself.

It depends on what you consider normative:  @pmconrad is considering the text displayed by the UI to be normative; I was considering the backend behavior we originally intended to implement to be normative.

We'll have to discuss this more internally.

**Comment by abitmore** [comment]
Below are some thoughts which I've posted in the forum thread:

> Assume account A is registered by account B (the registrar), and referred by account C (the referrer).
> 
> Before A upgraded to annual member, when A pays a fee, it splits for example as 20% network + 25% registrar + 55% referrer.
> 
> After A upgraded to annual member, when A pays a fee, it should split as 20% network + 50% A + (1-20%-50%)_25%/(1-20%)=9.375% registrar + (1-20%-50%)_55%/(1-20%)=20.625% referrer.
> 
> I remember in the code there are "lifetime referrer", "registrar", "referrer", imo they should all be different in this scenario. Imo "lifetime referrer" should be A, and "registrar" and "referrer" should be whatever unchanged.

**Comment by abitmore** [comment]
According to the code, when an account is created (https://github.com/bitshares/bitshares-2/blob/2.0.160128/libraries/chain/account_evaluator.cpp#L121-L136), following fields will be set:
- `registrar`
- `referrer`
- `lifetime_referrer` (= `referrer.lifetime_referrer`)
- `network_fee_percentage` (global parameter, now 20%)
- `lifetime_referrer_fee_percentage` (global parameter, now 30%)
- `referrer_rewards_percentage` (set by registrar).

When an account upgraded to annual subscriber (https://github.com/bitshares/bitshares-2/blob/2.0.160128/libraries/chain/account_evaluator.cpp#L274-L280), 
- `referrer` will be set to the account itself

When a fee is paid (https://github.com/bitshares/bitshares-2/blob/2.0.160128/libraries/chain/account_object.cpp#L81-L118), 
- fee cut to network first (now 20% \* total_fee), 
- then cut to lifetime_referrer(now 30% \* total_fee), 
- the rest(50%) then cut some to referrer(50%*referrer_rewards_percentage), 
- then cut the rest to the registrar. 

(According to https://bitshares.org/referral-program/, annual subscribers "also qualify for **up to** 50% of the fees paid by anyone they refer" when `referrer_rewards_percentage` is set "**up to**" 100%, and in this case the registrar will get no referral income.)

When an annual subscriber pays a fee, in order to "earn 50% cash back" (according to https://bitshares.org/referral-program/), since only `referrer` is set to the user herself, `referrer_rewards_percentage` should also be set to 100%.

Conclusion: current code implemented that "an annual subscriber will earn **up to** 50% cash back and qualify for **up to** 50% of the fees paid by anyone they refer", but the real number depends on the registrar who registered her (50% if referrer_rewards_percentage set to 100%, 0% if referrer_rewards_percentage set to 0%). Most people won't agree it's correct.

By the way, who is that "lifetime_referrer"? If A referred B, B referred C, C referred D, all these account will have a same "lifetime_referrer", and she'll gain 30% cut of fees paid by all these accounts no matter how much the referrer_rewards_percentage is. Looks like a Pyramid scheme?

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#153
