### ISSUE TITLE
Prediction market info fields

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene#544]
It would be nice to have more specific info fields for a prediction market asset. Currently we only have the "description" field which I suppose could encode a serialized JSON object with more details; but that would not be very practical for consumers or creators.

How about adding a prediction_market_info field to prediction market assets that could contain something like this:

```
{
   prediction: "BTS to the moon by 2017 or not", (short description of the prediction)
   expiry: "1/1/2017",
   primary_markets: ["USD", "BTS"] (used to direct users to specific markets) 
}
```

I'm sure we could come up with some more that would be useful, just brainstorming here.

This object could be nested inside the bitasset_data object, and simply be null for non-prediction market assets.

**Comment by theoreticalbts** [comment]
- What is the meaning of `primary_markets`?  Like any BitAsset, a PMA has a backing asset, and the PMA must be created by shorting the backing asset.  The largest market for a PMA is probably going to be the PMA against its backing asset (although other markets can exist).  Putting `primary_markets` in a field accomplishes exactly what purpose?
- What is the semantics of `expiry`?  Does anything happen on that date?

Also, could you explain precisely how setting the "description" field to a JSON object is impractical?  It seems to me that if this information can only be created/updated by the owner asset and has no relevance to validation, putting it in the description field is incredibly practical, as it separates the concerns (_this_ information is used only for presentation, _that_ information is needed for validation).

I admit we've been lax about allowing things into core that are only needed for the UI, but just because we've made questionable design decisions in the past doesn't mean we ought to keep on making them.

**Comment by svk31** [comment]
Primary markets would be a way for the asset creator to indicate which markets he will be focusing on, for example through marketing or by providing liquidity. If he wants it to trade mainly against USD for example he could indicate that, and the GUI would link to that market by default instead of to the :BTS market.

Expiry: Most predictions have a time condition, ie what will be the price of Oil on 1/1/2017. The expiry field would allow the creator to indicate this, and we could then filter out that asset after the expiry date because it's no longer a valid market.

While I agree that the description field can be quite useful, my experience from BTS 1 is what tells me it's impractical. We tried that with delegate info and most delegates never used it.

That being said the more I think about it the more it makes sense to use the description field. I could modify the GUI to serialize a JSON object which would allow asset owners to set all kinds of parameters. I should even add this for standard assets I'm thinking now.
