### ISSUE TITLE
Letting settlement_price expire would allow to reuse symbols for prediction markets

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene#546]
Borrowing an asset in a prediction market only works if there was no settlement yet in that asset.

I would propose to let `settlement_price` expire similar to `feed_prices` as defined in the bitassets options IFF the asset is a prediction market and IFF no outstanding debt positions are open (i.e. supply is 0).

That way we can reuse PMs after settlement if we put a 14 days expiration and using `override_transfer` to get the assets from the holders, close their positions for them and return whatever is returned from collateral (if at all)

**Comment by theoreticalbts** [comment]
Early in the design of Graphene, a deliberate decision was made that an asset name always represents the same asset object.

I've always personally thought the name-to-ID mapping should be mutable (but heavily rate-limited and time-locked, so e.g. changing the name of an asset would take 30 days and re-mapping the name to a new asset would take an additional 30 days).  This view was vindicated by the fact that some national currency BitAssets which were very illiquid have already experienced black swans, meaning no future asset can ever be issued with those names (which are undoubtably valuable names due to being widely recognized national currency symbols).

`override_transfer` is a very heavy-handed asset flag, it effectively makes the asset completely centralized (because the issuer can take it back at any time).  Making the symbol-to-asset-ID mapping mutable is a less heavy-handed way to implement the desired feature of symbol re-use.

**Comment by theoreticalbts** [comment]
Although I think it's a good idea to be able to experiment with symbol re-use, this is something that needs a lot of discussion both internally and in the community.  This is a low priority.

**Comment by xeroc** [comment]
> This is a low priority.

That is unfortunate but we can live with it since those in need can simply create a new asset.

Concerning the SEK and RUB assets that had a black swan: It is **very** unfortunate that it currently seems unfixable. This should certainly be discussed and I think ways should exist to "restart" a MPAs (or PM) after a certain amount of time

**Comment by bytemaster** [comment]
The issue is that if even a single user fails to settle then they can lock up the entire asset. Considering a single user forgetting their keys you have a problem.

Also the amount of computation (and therefore fees) involved can be more than can be processed in a single block.

Lastly not all balances are in the position to be "settled on demand", if BitUSD is being used as collateral for another asset or an asset is in escrow or a vesting balance or any place where the owner is indeterminate or where changing the asset id would break the contract then the whole thing breaks.

The best we could hope for is to rename the asset symbol and then reuse the old symbol. In other words, the asset_id can never change but the symbol is ultimately just a human readable name.

**Comment by xeroc** [comment]
This went a little off-topic.
My request was for prediction markets, which shouldn't be used as collateral at all. Those users that have not manually set their "long" position, could taken away the position via "overwrite_transfer", then the issuer can settle it and return the collateral (if prediction market has been resolved to `1.0`).
By this we could get back to a supply of `0` which makes the settlement_price kind of irrelevant and the asset could be restarted. Prediction markets would this be identified mainly from their description.

**Comment by theoreticalbts** [comment]
> The best we could hope for is to rename the asset symbol and then reuse the old symbol. In other words, the asset_id can never change but the symbol is ultimately just a human readable name.

Yes, this is exactly what I was suggesting -- symbols should be re-assignable to new assets.

**Comment by xeroc** [comment]
> symbols should be re-assignable to new assets.

All fine, but how does this help for the OP? I would like to reduce the flood of assets that we might see with prediction markets by allowing them to be reopened after settlement. Or do we want to store thousands of (PM) assets that have been settled and are thus dead?

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#154
