### ISSUE TITLE
Changing active keys should require owner authorities

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#556]
According to https://github.com/cryptonomex/graphene/blob/a1e8fc07417407525482924df6b125d95c38a06f/libraries/chain/include/graphene/chain/protocol/account.hpp#L131-L132 :

> New active authority. If set, this operation requires owner authority to execute.

which means owner authority is required when updating active authority.

But in develop branch it hasn't been validated: https://github.com/cryptonomex/graphene/blob/a1e8fc07417407525482924df6b125d95c38a06f/libraries/chain/include/graphene/chain/protocol/account.hpp#L145-L146 

Also in bitshares branch it hasn't been validated:
https://github.com/bitshares/bitshares-2/blob/d0609e8e7404845f526c72fa4ead05065f374e8b/libraries/chain/include/graphene/chain/protocol/account.hpp#L120-L121

**Comment by theoreticalbts** [comment]
I'll bring this to the attention of @bytemaster but I'm pretty sure the most we can do is change the documentation, because changing the behavior would effectively lock the account of anyone who's set up their key infrastructure relying on the current behavior.

**Comment by pmconrad** [comment]
IMO the distinction between active and owner keys is useless if the active key has the same (full) control of the account as the owner.
Requiring the owner key to modify the active key is a useful (security) feature.
I don't see a use case where someone would set up an account in such a way that he has no control over the owner key. That would be extremely counterintuitive, and it would be dangerous in light of the documented behaviour.

**Comment by roadscape** [comment]
Agree with @pmconrad. Useful security feature IMO. I don't think I read anywhere that's how it was supposed to work, it just seemed the most logical.

Although if someone has the active key, they have access to "everything" already, so perhaps it doesn't matter if they can change the key itself. In either case the owner's only power is to override the active key, afaik.

**Comment by xeroc** [comment]
Shouldn't there be at least a check for owner permission?
https://github.com/cryptonomex/graphene/blob/a1e8fc07417407525482924df6b125d95c38a06f/libraries/chain/protocol/account.cpp#L222-L227

@theoreticalbts

**Comment by abitmore** [comment]
@xeroc the permission is not check here, it's at 
https://github.com/cryptonomex/graphene/blob/f85dec1c23f6bf9259ad9f15311b2e4aac4f9d44/libraries/chain/protocol/transaction.cpp#L255-L256 and https://github.com/cryptonomex/graphene/blob/f85dec1c23f6bf9259ad9f15311b2e4aac4f9d44/libraries/chain/protocol/transaction.cpp#L275-L288
which will call https://github.com/cryptonomex/graphene/blob/f85dec1c23f6bf9259ad9f15311b2e4aac4f9d44/libraries/chain/protocol/operations.cpp#L99-L105
which wll call https://github.com/cryptonomex/graphene/blob/a1e8fc07417407525482924df6b125d95c38a06f/libraries/chain/include/graphene/chain/protocol/account.hpp#L145-L146

**Comment by xeroc** [comment]
Thanks

**Comment by theoreticalbts** [comment]
Yeah, the set of auths required for a given op is something that we have to expose externally to help the wallet decide which of the user's keys need to sign, so we have the framework call that.

Also by not having access to the DB, it enforces one of the design decisions of Graphene, which is that you don't need chain state to decide who signs.  That's why we have things like `asset_update_operation` which requires you to specify both asset ID and issuer account ID -- yes, you can get the latter if you know the former, but only if you have access to chain state.  Which `get_required_whatever()` doesn't.  And of course we assert the purported issuer in the op (used to determine who signs) matches the actual issuer (in the chain state), otherwise Bad Things Would Happen (anyone would be able to update any asset by claiming they're the asset owner).

**Comment by theoreticalbts** [comment]
Fixed, merged.

**Comment by abitmore** [comment]
Anyway good to see a decision has been made. Please remove the labels of this ticket.
