### ISSUE TITLE
CORE_ASSET.core_exchange_rate.is_null() == true

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#567]
Please be aware.

**Comment by theoreticalbts** [comment]
- Is there any bug being caused by this?
- Is there any concrete suggestion of what should be done about this?

I think the resolution is to add a line to the doc comment explaining what the semantics should be when `core_exchange_rate.is_null()` and under what circumstances it should occur, then audit that the evaluators enforce these circumstances for asset CRUD.

**Comment by abitmore** [comment]
No bug has been found except in my developing branch. CER is needed for percentage based transfer fee feature to calculate the value of a transfer. All assets created or updated in bitshares 2.0 have valid CERs. All assets except core asset inherited from bitshares 0.x have null CERs, they can't apply percentage fee unless set a valid CER. So I encountered this issue [here](https://github.com/abitmore/bitshares-2/commit/d28b9c5734bf7c9b74a203955dcfb3ac36dd505c) when trying to apply percentage fee to core asset.

In asset_update_operation, CER is validated thus `is_null()==false`. However CER of core asset is [invalid](https://github.com/bitshares/bitshares-2/blob/2.0.160208/libraries/chain/protocol/asset.cpp#L136) and it will never be updated. So I think it's ok to [leave it as is](https://github.com/bitshares/bitshares-2/blob/2.0.160208/libraries/chain/protocol/asset.cpp#L130), and be careful. Or fix it.

**Comment by theoreticalbts** [comment]
I discovered you can register new assets with null CER as well, see #579

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#155
