### ISSUE TITLE
new_options should be optional in asset_update_operation

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#580]
`new_options` should be optional allowing `asset_update_operation` with semantics of "don't change the options" (but maybe change the issuer).

It's going to be hard to implement this change without breaking protocol compatibility.

**Comment by abitmore** [comment]
I've done something related. CER could be optional in [this commit](https://github.com/abitmore/bitshares-2/commit/78d977b24c30a3b128870bd3db19d34eaf97d632). Need a pull request?

In regards to other options, I think maybe only `blacklists` and `whitelists` will matter since they may be large arrays. And maybe `asset_description`.

[Here](https://bitsharestalk.org/index.php/topic,20870.0.html) is a serious (GUI) bug report related, don't know whether it's fixed so I just submitted [an issue](https://github.com/cryptonomex/graphene-ui/issues/737) to graphene_ui repo.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#170
