### ISSUE TITLE
fee for clearing expired order was capped at deferred_fee 0?

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#589]
With the release 2.0.160216, while replaying, I noticed following warnings in logs:

```
   86.6228%   3066000 of 3539484
261508ms th_a       db_update.cpp:274             operator()           ] At block 3067959, fee for clearing expired order 1.7.28518 was capped at deferred_fee 0
   86.6793%   3068000 of 3539484

   93.5165%   3310000 of 3539484
281752ms th_a       db_update.cpp:274             operator()           ] At block 3311044, fee for clearing expired order 1.7.34171 was capped at deferred_fee 0

```

Questions:
- Actually the first cancel is at block 3067958, see https://cryptofresh.com/b/3067958.
- In the link above it paid a fee. But in the new log it says 0 fee.
- I don't think that order was partially filled. 

@theoreticalbts ?

**Comment by abitmore** [comment]
Related to #549

**Comment by abitmore** [comment]
I didn't find any cancelled order around block 3311044 from https://cryptofresh.com/b/3311044 . I checked from block 3311040 to block 3311049.

**Comment by theoreticalbts** [comment]
This logging statement applies to _expired_ orders.  The cancel op for an expired order is a virtual op (v-op).  The cryptofresh UI does not show v-ops.  The cancel op you're seeing in the first block is an unrelated, user-initiated cancel for a different order `1.7.31916`, and that cancel _does_ pay a fee.

I discussed these logging statements with @bytemaster prior to release, and we agreed that the new behavior is acceptable.  Mostly our discussion centered around the fact that this was the path of least resistance (since it's what I had implemented as of yesterday), but it's just occurred to me that there's actually a much better justification for the new behavior.

When creating a market transaction, you say "the most fees I'm willing to pay is X" where X is the fee that actually goes into the order (which is routed to `deferred_fee`).  If the chain decided to cancel the order due to expiration, the old logic would reach into the user's account and pull out an _additional_ fee if the `deferred_fee` was insufficient (for example if it was cleared due to a partial fill).  The old logic was basically violating the smart contract the user signed by taking an amount greater than X for the fee, the additional amount (what it reached into the user's account to take out) was "unfair" because the user never authorized the system to take it.

So the right thing to do is to refund those "unfair" fees to the people who paid them, which is exactly what the new code effectively does (well, it re-writes history so they were never charged in the first place).  The logging statement is simply showing each such refund as it occurs.

Very few refunds occur (I believe I only saw 3) and each one is equal to a cancel fee, so it's not like there's a huge amount of people / funds affected by this issue.

No action is necessary on this ticket, but I'll leave it open for now so people can easily find it.

**Comment by abitmore** [comment]
Yes, you're right. I forgot that the cancel order in block 3067958 is another one, I should have noticed it.

So the real order expired at block 3067959 is 

```
{  
   "id":"1.7.28518",
   "expiration":"2016-01-28T23:15:15",
   "seller":"1.2.96709",
   "for_sale":147060078,
   "sell_price":{  
      "base":{  
         "amount":971562659,
         "asset_id":"1.3.0"
      },
      "quote":{  
         "amount":8540828,
         "asset_id":"1.3.103"
      }
   },
   "deferred_fee":0
}
```

The v-op (cancel on expiration) before release `2.0.160216` was

```
{
  "id": "1.11.1124074",
  "op": [
    2,
    {
      "fee": {
        "amount": 10000,
        "asset_id": "1.3.0"
      },
      "fee_paying_account": "1.2.96709",
      "order": "1.7.28518",
      "extensions": [

      ]
    }
  ],
  "result": [
    2,
    {
      "amount": 147060078,
      "asset_id": "1.3.0"
    }
  ],
  "block_num": 3067959,
  "trx_in_block": 1,
  "op_in_trx": 2,
  "virtual_op": 41464
}
```

The v-op (cancel on expiration) after release `2.0.160216` is

```
{
  "id": "1.11.1124074",
  "op": [
    2,
    {
      "fee": {
        "amount": 0,
        "asset_id": "1.3.0"
      },
      "fee_paying_account": "1.2.96709",
      "order": "1.7.28518",
      "extensions": [

      ]
    }
  ],
  "result": [
    2,
    {
      "amount": 147060078,
      "asset_id": "1.3.0"
    }
  ],
  "block_num": 3067959,
  "trx_in_block": 1,
  "op_in_trx": 2,
  "virtual_op": 41464
}
```

Looks all fine. Don't know what's the number after "virtual_op" though.
Thanks.

**Comment by theoreticalbts** [comment]
There's actually nothing to be done here, so I'm just going to close this.
