### ISSUE TITLE
Potential something-for-nothing fill bug

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#601]
This report from @svk31 on Slack:

something strange appears to have happened in the BTS:METAEX.BTC market: an order appears to have happened where someone paid 0 METAEX.BTC and received 1 satoshi BTS, making the price go to infinity or zero depending on your market direction

it's causing issues in the GUI when looking at that market

Possible duplicate of #555

**Comment by theoreticalbts** [comment]
order_id in question is 1.7.104874

**Comment by svk31** [comment]
We're getting a lot of these at the moment, would be great if this could get looked at sooner rather than later. As you can see from the below screenshot it causes the price to go to 0, and in the inverse market direction the charts fail due to Inf values..

![image](https://cloud.githubusercontent.com/assets/6890015/13595899/400d5400-e50f-11e5-9875-ab676b04af8a.png)

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#184
