### ISSUE TITLE
`get_full_account` should return `vesting_balance_object_with_info`

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene#626]
`get_full_account` should return `vesting_balance_object_with_info` instead of
`vesting_balance_object`.

That would allow the wallet to easily show the vesting balances and withdraw-able amounts but would probably result in additional load at the witness node.

Is there an alternative way to let the witness derive the "allowed_withdraw" parameter of a vesting balance?

**Comment by theoreticalbts** [comment]
Um, the `get_allowed_withdraw()` algorithm for each vesting policy is in `vesting_balance_object.cpp`.  In principle, you can re-implement this algorithm in whatever's calling the witness node, but it requires `uint128_t` math, which might not be so easy in JS.

The other problem is that the derived fields of `vesting_balance_with_info` won't update.  Being allowed to withdraw more because time has passed doesn't result in an object update, rather the time passed into `get_allowed_withdraw()` is different.  This allows VBO's to vest continuously over time without burdening the chain too much.  Moreover updating these fields when there's a deposit / withdrawal to/from the VBO would require special-casing in the subscription logic.

The real solution is, if you want to do fancy things with `get_allowed_withdraw()` in your UI, you want to simply re-implement the functionality at the UI level.  If that's too hard, then you can always just call `get_vesting_balances()` which does return the VBO.

**Comment by abitmore** [comment]
Just a note here, the rate limited free transaction feature (#603) has a similar function `compute_coin_seconds_earned()` which requires `uint128_t` math as well, so it's best if UI has a `uint128_t` implementation.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#195
