### ISSUE TITLE
Audit fee calculations, set fees

### ISSUE THREAD

**Issue by nathanielhourt** [cryptonomex/graphene#66]
Make sure all operations have a solid implementation of `calculate_fee`, specifically looking for:
- Creations are fairly expensive
- Updates are proportional to their data size
- Deletions are cheap
- Any operation with a list or set pays proportional to its size
  Add items to fee schedule as necessary. Set initial fee values in schedule.

**Comment by nathanielhourt** [comment]
I've set the fee schedule with some values I handpicked. These are fairly arbitrary, but are intended to reflect some of the discussions we've had. Feel free to make changes. The numbers are set using the current value of BTS, with the following values in dollars:

```
key_create_fee ~= $0.020
account_create_fee ~= $0.049
account_update_fee ~= $0.011
account_transfer_fee ~= $0.022
account_len8up_fee ~= $0.111
account_len7_fee ~= $0.518
account_len6_fee ~= $1.036
account_len5_fee ~= $5.180
account_len4_fee ~= $20.720
account_len3_fee ~= $50.320
account_len2_fee ~= $74.000
asset_len3_fee ~= $518.000
asset_len4_fee ~= $199.800
asset_len5_fee ~= $99.900
asset_len6_fee ~= $49.950
asset_len7up_fee ~= $10.360
account_whitelist_fee ~= $0.022
delegate_create_fee ~= $50.320
witness_create_fee ~= $50.320
witness_withdraw_pay_fee ~= $0.111
transfer_fee ~= $0.200
limit_order_create_fee ~= $0.049
limit_order_cancel_fee ~= $0.011
call_order_fee ~= $0.059
publish_feed_fee ~= $0.049
asset_create_fee ~= $50.320
asset_update_fee ~= $0.011
asset_issue_fee ~= $0.052
asset_burn_fee ~= $0.111
asset_fund_fee_pool_fee ~= $0.011
asset_settle_fee ~= $0.518
data_fee ~= $0.999
global_parameters_update_fee ~= $0.100
membership_annual_fee ~= $19.980
membership_lifetime_fee ~= $99.900
withdraw_permission_create_fee ~= $0.200
withdraw_permission_update_fee ~= $0.011
withdraw_permission_claim_fee ~= $0.052
withdraw_permission_delete_fee ~= $0.011
vesting_balance_create_fee ~= $0.518
vesting_balance_withdraw_fee ~= $0.200
asset_global_settle_fee ~= $10.360
worker_create_fee ~= $50.320
assert_op_fee ~= $0.011
proposal_create_fee ~= $0.518
proposal_update_fee ~= $0.111
proposal_delete_fee ~= $0.011
```

**Comment by arhag** [comment]
Would it make sense to define a scaling parameter as part of the global parameters which scales all fee values? That way all the prices could be defined in USD (or any other relatively stable unit of account) but would be scaled to the BTS value by the scaling parameter. Then the delegates don't need to frequently submit transactions with 47+ new values. They would rarely change those values, but they would frequently change the one scaling parameter as the USD/BTS price changed.

Furthermore, perhaps changing the scaling parameter has different conditions than changing any of the other values. For example, it may have a shorter delay than the regular 2 week delay. Perhaps if the scaling parameter value was last changed due to a delegate proposal submitted more than 24 hours ago and the absolute value of the percentage difference between the new proposed value and the current value is less than some threshold, then the blockchain could accept the proposed change (assuming the change is only for the scaling parameter) with only an additional 24 hour delay.

**Comment by nathanielhourt** [comment]
@arhag I think something like that could be useful. I was thinking it would be somewhat onerous to be updating these values all the time.

**Comment by nathanielhourt** [comment]
Do we want to add a fee scaling parameter which can be updated daily, or can we close this issue?

**Comment by vikramrajkumar** [comment]
Related: #141

**Comment by bytemaster** [comment]
After working on #144 I would consider them throughly audited because everything was reimplemented.
