### ISSUE TITLE
Are fee schedule integer sizes big enough?

### ISSUE THREAD

**Issue by emfrias** [cryptonomex/graphene#99]
Right now we have a mix of `uint32_t` and `uint64_t`s for the various fees in `fee_schedule_type`.  They're all large enough to hold their default values, but some of the `uint32_t` types don't leave us a lot of room to adjust up in the future.  For example, `asset_create_fee` is 2500000000.  We can only increase that by ~40% before overflowing, so if we decide it needs to be more expensive or if CORE drops against USD by that amount, we'll have problems.

I assume this structure will only be transmitted on the network infrequently with `global_parameters_update_operation`.  Can we just bite it on a few hundred bytes and make 'em all `uint64_t`?

https://github.com/cryptonomex/graphene/blob/master/libraries/chain/include/graphene/chain/types.hpp#L350-L397

**Comment by arhag** [comment]
Personally, I think it makes a lot of sense to just make all fee values into uint64_t and be done with, because as you said these should be updated very infrequently, _as long as_ you also implement a scaling parameter (see https://github.com/cryptonomex/graphene/issues/66#issuecomment-114676452) on all the fee values where the scaling parameter can be updated independently.

Another optimization that could be done (although likely not worth it) is to have a bit field defining which of the parameters in the global parameters (which would require a specified sequence in their definition) are being updated in the global_parameters_update_operation and only include the update values in the transaction. That means the number of uint64_t values included in the transaction would be equal to the number of 1 bits in the accompanying bit field.

**Comment by bytemaster** [comment]
The real reason was the minimize the size of the "largest operation" because every operation reserves space for the "largest" one.   Right now that space is being largely dominated by this fee structure.  

With a little work we could dynamically allocate the fee schedule in the operation and bypass this concern.

**Comment by theoreticalbts** [comment]
Fee types all increased to `uint64_t`.  Dynamic allocation is a separate discussion, let's continue it in a new ticket (#109).
